// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Final.Models;

namespace WebApi_Final.Migrations
{
    [DbContext(typeof(MusicaContext))]
    partial class MusicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_Final.Models.Album", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("AlbumFec")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlbumTit")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CantanteId")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("GeneroId")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PaisId")
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("AlbumId");

                    b.HasIndex("CantanteId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PaisId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("WebApi_Final.Models.Cantante", b =>
                {
                    b.Property<string>("CantanteId")
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CantanteName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaisId")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CantanteId");

                    b.HasIndex("PaisId");

                    b.ToTable("Cantantes");
                });

            modelBuilder.Entity("WebApi_Final.Models.Genero", b =>
                {
                    b.Property<string>("GeneroId")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("GeneroName")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("WebApi_Final.Models.Pais", b =>
                {
                    b.Property<string>("PaisId")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Pais_Nom")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("WebApi_Final.Models.Album", b =>
                {
                    b.HasOne("WebApi_Final.Models.Cantante", "Cantante")
                        .WithMany()
                        .HasForeignKey("CantanteId");

                    b.HasOne("WebApi_Final.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId");

                    b.HasOne("WebApi_Final.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.Navigation("Cantante");

                    b.Navigation("Genero");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("WebApi_Final.Models.Cantante", b =>
                {
                    b.HasOne("WebApi_Final.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
